version: "3.9"

services:
  database:
    image: postgres
    container_name: db_fin_api
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_fin_api
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: fin_api
    restart: always
    ports: 
      - 3330:3330
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local